---
title: "Homework: week_02/day3"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
```

```{r}
# Programming in R Homework - Answers
# 1 MVP
# 
# Question 1.
# Find the weather forecast for the next three days online. Create a list of lists in which each inner list should be labelled with the name of the day of the week. Each inner list should contain named elements telling you the temperature, chance of rain and wind speed.
#

forecast <- read_csv("forecast_data.csv")
view(forecast)
forecast <- clean_names(forecast)

forecast_list <- list(
  "Thursday" = list(temperature = 14.2, chance_of_rain = 85.6, wind_speed = 10.5),
  "Friday"   = list(temperature = 14.6, chance_of_rain = 71.4, wind_speed = 4.1),
  "Saturday" = list(temperature = 13.2, chance_of_rain = 52.4, wind_speed = 5.6)
)

forecast_list

```


```{r}
# 
# Question 2.
# Using the list you’ve just made find:
# 
#     The chance of rain tomorrow
#     The wind speed on the day after tomorrow
#     The temperature tomorrow.
#

forecast_list$Thursday$chance_of_rain
forecast_list[[1]][3]
forecast_list$Thursday$temperature
```


```{r}
# 
# Question 3.
# Find a 14 day forecast online and create a matrix of the forecasts for temperature, where each week is one row and columns correspond to days.
# 
# You will want to give a name to the matrix you create.
#

temperature <- forecast %>% 
  slice(2:15) %>% 
  pull(temperature)

forecast_matrix <- matrix(temperature, nrow = 2, ncol = 7, byrow = TRUE)
```


```{r}
# 
# Question 4.
# From the matrix you just made select:
# 
#     The third day of the second week
#     The whole second week
#     The first, third and fifth days in both weeks.
#

forecast_matrix[2, 3]
forecast_matrix[2, ]
forecast_matrix[ , c(1,3,5)]
```


```{r}
# 
# Question 5.
# Write a function that pre-appends “The answer is:” to any character input, while for numeric input, it either just returns the number for numbers less than 10, or divides the number by 10 for numbers greater than 10. For anything else return “Invalid input”.
#

function_5 <- function(x){
  if (is.numeric(x) & x < 10){
      print(x)
  }
  if (is.numeric(x) & x > 10){
    print(x / 10)
  }
  if (is.character(x)){
    print(str_c("The answer is: ",x))
  }
  if (!is.character(x) & !is.numeric(x)){
    print("Invalid input")
  }
}

function_5(100)
function_5("hello")
function_5(TRUE)
```

```{r}
# 
# Question 6.
# Write a function which checks if two vectors have the same elements.
# 
#     If they have the same elements in the same order, return “Exactly the same”
#     If they have the same elements but in a different order, return “The same”
#     If they don’t have the same elements, return “Different”.
# 
# Hints
# 
#     You can check if two vectors have the same elements but in a different order by using sort to sort each vector first and then checking if they are equal.
#     Have a look at the all() function


```

