---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(CodeClanData)
library(tidyverse)
```

```{r}

qb_revenue_breakdown
qb_monthly_sales
qb_competitors
qb_device_data
    
```

```{r}
# 2 MVP
# 2.1 Part 1
# 
# Question 1.
# Take the data in the dataset qb_revenue_breakdown and make a stacked bar chart showing the sources of revenue across the two years in the dataset.

ggplot(qb_revenue_breakdown) +
  aes(x = Year, y = Revenue, fill = Product) +
  geom_bar(stat = "identity")

```


```{r}
# Questino 2.
# Make a line chart showing monthly sales of the “flagship product” - the ‘KwikBit Unit 1’ - over the last year. This data is inside qb_monthly_sales, but you will need to use filter() or subset() (base R).
#

view(qb_monthly_sales)
  
qb_monthly_sales %>% 
  filter(Cashflow == "Kwikbit Unit 1 Sales") %>% 
  ggplot() +
  geom_line(aes(x = Date, y = Amount))

```


```{r}
# Question 3.
# Make a line chart showing monthly revenue and costs over the last year. This data is also in qb_monthly_sales.
#

qb_monthly_sales %>% 
    filter(Cashflow != "Kwikbit Unit 1 Sales") %>% 
ggplot() +
  aes(x = Date, y = Amount, group = Cashflow, colour = Cashflow) +
  geom_line()

```


```{r}
# Question 4.
# Show annual sales of personal fitness trackers over the last 5 years broken down by company as a ribbon plot (use geom_area). This data is in qb_competitors.
#

view(qb_competitors)

ggplot(qb_competitors) +
  aes(x = Revenue, y = Company, group = Company, fill = Company) +
  geom_area(stat = "identity")

```


```{r}
# Question 5.
# Now show the sales from the four competitors as a line graph. Include an extra layer that shows the data points used to make the lines.
#

ggplot(qb_competitors) +
  aes(x = Year, y = Revenue, colour = Company) +
  geom_line(aes(group = Company)) +
  geom_point()

```


```{r}
# Question 6.
# Now the company wants to compare the number of steps that their device counts vs. their competitors. Make a line graph of the number of steps throughout time, and use faceting to compare between companies and people. The data for this is in qb_device_data. 
#

view(qb_device_data)

ggplot(qb_device_data) +
  aes(x = hours, y = counts, colour = id) +
  geom_line(aes(group = device)) +
  facet_wrap(~device)

ggplot(qb_device_data) +
  aes(x = hours, y = counts, colour = device) +
  geom_line(aes(group = device)) +
  facet_wrap(~id)
```

```{r}
# 2.2 Part 2
# 
# Question 1.
# Take the plots that you produced in part one and now polish them by:
# 
#     Adding appropriate labels
#     Changing the scales and coordinates when appropriate.
#     Applying a unified theme, which is described below:
# 
#     Graphs should have white backgrounds, and use colour sparingly.
#     There should be faint grid lines.
#     Font sizes should be ~12pt although titles should be slightly larger and axis labels can be slightly smaller.
#     All plots should use colours from the following company colour scheme.
# 
# col_scheme <- c("#E89FE9", "#50434F", "#B6A7B5", "#F9A472", "#BD7040")

ggplot(qb_revenue_breakdown) +
  aes(x = Year, y = Revenue, fill = Product) +
  geom_bar(stat = "identity")

```

